#
# Dailex project settings.
#

name: Dailex
description: 'Daikon CQRS & ES integration with the Silex framework'
prefix: dailex
framework:
  trusted_proxies:
    - 0.0.0.0/0
email:
  from_email: dailex@dailex.dev
  from_name: Dailex
translation:
  default_locale: en
  locale_fallbacks:
    - en
    - de
    - fr
    - es
    - ja
    - ar