testing.blog.event_store:
  connector: dailex.event_store
  settings:
    database: ${project.prefix}%2Btesting-blog

testing.blog.message_queue:
  connector: dailex.message_queue
  settings:
    vhost: /

testing.blog.message_queue.admin:
  connector: dailex.message_queue.admin
  settings:
    vhost: "%2f"

testing.blog.projection_store.standard:
  connector: dailex.projection_store.standard
  settings:
    index: ${project.prefix}.testing-blog

testing.blog.filesystem:
  connector: dailex.filesystem
  settings:
    mounts:
      migration:
        adapter: League\Flysystem\Adapter\Local
        location: ${app.dir}/crates/testing-blog/migration