migration_loaders:
  testing.blog.event_store:
    class: Daikon\Flysystem\Migration\FlysystemMigrationLoader
    connector: testing.blog.filesystem
    settings:
      location: migration://couchdb

  testing.blog.projection_store.standard:
    class: Daikon\Flysystem\Migration\FlysystemMigrationLoader
    connector: testing.blog.filesystem
    settings:
      location: migration://elasticsearch

  testing.blog.message_queue:
    class: Daikon\Flysystem\Migration\FlysystemMigrationLoader
    connector: testing.blog.filesystem
    settings:
      location: migration://rabbitmq

migration_adapters:
  testing.blog.event_store:
    class: Daikon\CouchDb\Migration\CouchDbMigrationAdapter
    connector: testing.blog.event_store

  testing.blog.projection_store.standard:
    class: Daikon\Elasticsearch5\Migration\Elasticsearch5MigrationAdapter
    connector: testing.blog.projection_store.standard
    settings:
      type: testing-blog-migration_list

  testing.blog.message_queue:
    class: Daikon\RabbitMq3\Migration\RabbitMq3MigrationAdapter
    connector: testing.blog.message_queue.admin
    settings:
      exchange: testing.blog.migration_list

migration_targets:
  testing.blog.event_store:
    enabled: true
    migration_adapter: testing.blog.event_store
    migration_loader: testing.blog.event_store

  testing.blog.projection_store.standard:
    enabled: true
    migration_adapter: testing.blog.projection_store.standard
    migration_loader: testing.blog.projection_store.standard

  testing.blog.message_queue:
    enabled: true
    migration_adapter: testing.blog.message_queue
    migration_loader: testing.blog.message_queue